apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quibbble-corner.fullname" . }}
  labels:
    {{- include "quibbble-corner.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "quibbble-corner.selectorLabels" . | nindent 6 }}
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "quibbble-corner.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: quibbble-corner
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.port }}
          initialDelaySeconds: 3
