apiVersion: v1
kind: Service
metadata:
  name: {{ include "quibbble-corner.fullname" . }}
  labels:
    {{- include "quibbble-corner.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "quibbble-corner.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
