# Default values for quibbble-corner

replicaCount: 1

port: 8080

ingress:
  enabled: false
  annotations: {}
  path: /
  pathType: ImplementationSpecific
  hosts: []
  # - name: ""
  #   tls:
  #     enabled: false
  #     secretName: ""
  ingressClassName: nginx

image:
  repository: docker.io/quibbble/qcorner
  tag: latest
  pullPolicy: IfNotPresent

# This secret is created for you if no 'cornerSecretName' is specified.
# Otherwise create a secret with these same data parameters and use it by
# setting the 'cornerSecretName' field with the name of the secret.
# 
# kind: Secret
# apiVersion: v1
# metadata:
#   name: quibbble-corner
# type: Opaque
# data:
#   admin-password: <base64_encoded admin password>

cornerSecretName: ~
admin:
  username: quibbble
  password: ~

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
nodeSelector: {}
affinity: {}
tolerations: []
