# Default values for quibbble-corner

replicaCount: 1

port: 8080

ingress:
  enabled: false
  annotations: {}
  path: /
  pathType: ImplementationSpecific
  hosts: []
  # - name: ""
  #   tls:
  #     enabled: false
  #     secretName: ""
  ingressClassName: nginx

image:
  repository: docker.io/quibbble/qcorner
  tag: latest
  pullPolicy: IfNotPresent

# This secret is created for you if no 'cornerSecretName' is specified:
# 
#  apiVersion: v1
#  kind: Secret
#  data:
#    admin-password: <base64_encoded admin password>
#  type: Opaque
cornerSecretName: ~
admin:
  username: quibbble
  password: ~
